$
$ ~~~~~~~~~~ OFFENSE ~~~~~~~~~~
$
$ ----- I Formation -----
$
$ Runs
$
"ISWEEPR"IR.HB8O.FBL TEL FLO SEA
"IDIVEL"IR.FB1C.HB8 TEH FLQ SEO
"ITRAPL"IR.QB5P.HBL FBL TEB FLH SEO
$
$ Screens
$
"ISCREENR"IR.SSHB.FB1 TEX FLO SEH
"ISCREENL"IR.SWFB.HB8 TEB FLQ SEO
$
$ Passes
$
"IFLOODR"IR.RS HB/I,12,-18/ FB/U,10,12/ TE/Y,10,6/ FLD SEA
"ICROSS"IR.PK HB/L,12,12/ FB/L,10,-12/ SEI TEX FLH
$
"IPOSTR"IR.PK HBQ FB/V,10,10/ TEI FLP SED
"IDEEPL"IR.RW HB/U,15,-20/ FB/T,6,-5/ TEA FLI SEF
$
$ Play Action
$
"IDRAW"IR.PK FB7 TEG FLO SEO;HB2
"IFAKES"IR.FB1C.HB/I,12,18/ TEW FLQ SEH;PK
"IFAKED"IR.HB8O.FBL TEA FLP SEF;RW
$
$ ----- Near Formation -----
$
$ Runs
$
"NSWEEPL"NR.HB7P.FBL TEB SEO FLA
"NDIVER"NR.FB4C.HBL TEO FLH SEI
"NTRAPR"NR.QB8+2P.HBL FBL TEL FLH SEQ
$
$ Screens
$
"NSCREENR"NR.SSHB.FB7 TED FLO SEQ
"NSCREENL"NR.SWFB.HB2 TEH FLQ SEG
$
$ Passes
$
"NSPREAD"NR.PK HB/U,10,6/ FB7 TEQ FLO SED
"NSHORT"NR.PK HB/I,10,0/ FB/U,6,12/ TEX FLD SEA
$
"NDEEP"NR.PK HBW FB/L,15,12/ TED FLP SEC
"NFLOODL"NR.RW HB/U,15,10/ FBA TEA FLA SEF
$
$ Play Action
$
"NDRAW"NR.PK HB/I,2,10/ TE/I,8,5/ FLH SEO;FB1
"NFAKES"NR.HB7P.FBL TEH FLO SEW;RS
"NFAKED"NR.FB4C.HBL TEO FLF SEP;PK
$
$ ----- Far Formation -----
$
$ Runs
$
"FSWEEPL"FR.FB5T.HBL TEH FLQ SED
"FDIVEL"FR.HB1C.FB7 TEO FLD SEQ
"FDIVER"FR.QB4CT.HB5 FB5 TEL FLO SEH
$
$ Screens
$
"FSCREENR"FR.SSFB.HBG TEQ FLB SEH
"FSCREENL"FR.SWHB.FB8 TEB FLH SEO
$
$ Passes
$
"FUNDER"FR.PK HB/U,10,5/ FB/I,5,10/ TE/Y,15,-5/ FLW SEO
"FINOUT"FR.PK HB/I,12,12/ FBH TE/I,10,10/ FLI SEI
$
"FSLANT"FR.PK HB/U,15,8/ FBH TE/I,12,12/ FL/U,30,-10/ SE/V,12,-15/
"FDEEP"FR.PK HBD FB/V,12,10/ TE/I,15,0/ FLO SEP
$
$ Play Action
$
"FDRAW"FR.PK HBG TE/I,5,8/ FLO SEH;FB2
"FFAKES"FR.HB1C.FB/I,5,-10/ TEQ FLI SEH;PK
"FFAKED"FR.FB5T.HBL TE/I,15,0/ FLC SEP;RS
$
$ ----- Open Formation -----
$
$ Runs
$
"OSWEEPR"OR.FB6WQ.HB1 TEL FLO SEA
"ODIVEL"OR.HB1C.FBL TEO FLH SEH
"OTRAPL"OR.QB7+2P.HBL FBL TEB FLH SEO
$
$ Screens
$
"OSCREENR"OR.SSFB.HB7 TEG FLD SEQ
"OSCREENL"OR.SWHB.FB8 TEQ FLH SEB
$
$ Passes
$
"OMIDDLE"OR.PK HBO FBO TE/U,15,-5/ FLQ SEQ
"OFLOODL"OR.RW HB/I,5,10/ FB/Y,15,-5/ TEX FLQ SED
$
"OFLOODR"OR.RS HB/V,20,12/ FBQ TED FLO SE/I,30,-10/
"ODEEP"OR.PK HB/I,20,0/ FBH TE/Y,15,5/ FLP SED
$
$ Play Action
$
"ODRAW"OR.PK FB/I,7,7/ TEH FLO SEO;HB1
"OFAKES"OR.FB6WQ.HB/I,10,0/ TEG FLW SEQ;PK
"OFAKED"OR.HB1C.FBL TE/Y,15,-5/ FLP SEF;PK
$
$ ----- One Setback Formation -----
$
$ Runs
$
"1SWEEPR"1R.FB8P.HBH TEL FLO SEO
"1DIVE"1R.FB1C.HB/I,8,8/ TE/I,8,8/ FLH SEH
$
$ Passes
$
"1FLOODR"1R.RS HBW FB8 TEO FLH SEQ
"1FLOODL"1R.RW HBD FB7 TEX FLI SEO
"1HOOK"1R.PK HBI FB/V,7,10/ TEX FLH SEH
$
"1DEEP1"1R.PK HBO FB/V,12,6/ TEI FLD SEP
"1DEEP2"1R.RW HB/Y,20,7/ FBI TE/I,6,-3/ FLD SE/V,15,-15/
"1DEEP3"1R.PK HB/Y,15,-5/ FB/U,12,-18/ TEO FLF SEO
$
$ Play Action
$
"1DRAW"1R.PK HBH TEO FLH SEO;FB3
"1FAKES"1R.FB1C.HBI TEX FLQ SEH;PK
"1FAKER"1R.FB1C.HBI TED FLF SEP;RS
"1FAKEL"1R.FB8P.HB/I,20,0/ TE/Y,15,-5/ FLP SEC;RW
$
$ ----- Shotgun Formation -----
$
$ Runs
$
"SGSWEEPL"GR.QB7+1P.HBL FBL TED FLQ SEO
"SGDIVE"GR.FB2C.HBO TEH FLO SEH
$
$ Screens
$
"SGSCREENR"GR.SSFB.HBO TEX FLF SEH
"SGSCREENL"GR.SWHB.FB8 TEO FLH SEO
$
$ Passes
$
"SGDEEP1"GR.PK HB/Y,20,-7/ FBD TE/I,15,0/ FLP SEF
"SGDEEP2"GR.PK HB/I,20,0/ FB/I,15,0/ TE/I,15,0/ FLC SEC
"SGDEEP3"GR.PK HB/U,20,7/ FB/Y,15,-5/ TE/Y,15,5/ FLF SE/U,30,-10/
"SGDEEP4"GR.PK HB/I,20,0/ FB/I,15,15/ TE/Y,15,-5/ FL/U,30,-10/ SEF
"SGDEEP5"GR.PK HB/I,20,0/ FBD TEI FLF SEI
$
$ Play Action
$
"SGDRAW"GR.PK HBO TEO FLO SEO;FB2
$
$ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
